---
# Gitpod Configuration
# ver: https://www.gitpod.io/docs/introduction/learn-gitpod/gitpod-yaml

# Uso de imagen de Docker específica
# ver: https://hub.docker.com/u/gitpod
image: gitpod/workspace-java-21

# Comandos a ejecutar al inicio del proyecto
tasks:
  - init: "echo 'Initializing...'"
  - command: "mvn spring-boot:run"

# Tarea adicional para compilar el proyecto sin ejecutar pruebas
  - name: Compila proyecto sin ejecutar pruebas
    before: |
      sdk install springboot 
    init: |
      if [ -f proyecto/pom.xml ]; then mvn package -DskipTests -f proyecto/pom.xml; fi
    command: |
      if [ -f docker-compose.yml ]; then docker compose up -d; fi

# Extensiones
vscode:
  extensions:
    - vscjava.vscode-java-pack
    - vmware.vscode-spring-boot
    - vscjava.vscode-spring-boot-dashboard
    - vscjava.vscode-spring-initializr
    - rangav.vscode-thunder-client
    - redhat.java
    - vscjava.vscode-gradle
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
